name: firecrawl

x-common-service: &common-service
  build: apps/api
  networks:
    - backend
  environment:
    - REDIS_URL=${REDIS_URL:-redis://redis:6379}
    - REDIS_RATE_LIMIT_URL=${REDIS_URL:-redis://redis:6379}
    - PLAYWRIGHT_MICROSERVICE_URL=${PLAYWRIGHT_MICROSERVICE_URL:-http://puppeteer-service:3000}
    - PORT=${PORT:-3002}
    - NUM_WORKERS_PER_QUEUE=${NUM_WORKERS_PER_QUEUE}
    - BULL_AUTH_KEY=${BULL_AUTH_KEY}
    - TEST_API_KEY=${TEST_API_KEY}
    - HOST=${HOST:-0.0.0.0}
    - SELF_HOSTED_WEBHOOK_URL=${SELF_HOSTED_WEBHOOK_URL}
    - LOGGING_LEVEL=${LOGGING_LEVEL}
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:
  puppeteer-service:
    build: apps/puppeteer-service-ts
    environment:
      - PORT=3000
      - PROXY_SERVER=${PROXY_SERVER}
      - PROXY_USERNAME=${PROXY_USERNAME}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
      - TWOCAPTCHA_TOKEN=${TWOCAPTCHA_TOKEN}
      - MAX_CONCURRENCY=${MAX_CONCURRENCY}
    networks:
      - backend

  api:
    <<: *common-service
    depends_on:
      - redis
      - puppeteer-service
    ports:
      - "3002:3002"
    command: ["pnpm", "run", "start:production"]

  worker:
    <<: *common-service
    depends_on:
      - redis
      - puppeteer-service
      - api
    command: ["pnpm", "run", "workers"]

  redis:
    image: redis:alpine
    networks:
      - backend
    command: redis-server --bind 0.0.0.0

networks:
  backend:
    driver: bridge
